devices:
trap:
  listen: 127.0.0.1:1620
  community: hello
  version: ""
  transport: ""
discovery:
  cidrs:
  - 10.10.0.0/24
  debug: false
  ports:
  - 161
  default_communities:
  - public
  default_v3: null
  add_devices: true
  add_mibs: false
  threads: 4
  replace_devices: true
global:
  poll_time_sec: 300
  drop_if_outside_poll: false
  mib_profile_dir: /etc/ktranslate/profiles
  mibs_db: /etc/ktranslate/mibs.db
  mibs_enabled:
  - IF-MIB
  timeout_ms: 3000
  retries: 0
